# Generated by Django 5.2.15 on 2026-07-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeprofile_joined_date_permission_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='group',
        ),
    ]
