# Generated by Django 5.2.15 on 2026-08-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_joined_date_role_is_active'),
        ('accounts', '0006_alter_customuser_id_alter_department_id_and_more'),
    ]

    operations = [
    ]
