# Generated by Django 5.2.15 on 2026-08-30 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_manager_from_department(apps, schema_editor):
    """
    Gán manager ban đầu = manager của phòng ban mà nhân viên đang thuộc.

    Bắt buộc phải có bước này. Sau migration, ManagerTeamEmployeeListView sẽ
    lọc theo profile.manager — nếu để trống toàn bộ thì mọi Manager mở danh
    sách nhân viên ra sẽ thấy rỗng và không giao được task cho ai.

    Department.manager là dữ liệu tổ chức đã có sẵn nên dùng làm điểm khởi
    đầu hợp lý nhất. Ai không suy ra được (phòng ban chưa có manager, hoặc
    chưa thuộc phòng ban nào) thì để NULL — Admin lọc "Chưa gán" trên trang
    User List để xử lý nốt bằng tay.
    """
    EmployeeProfile = apps.get_model("accounts", "EmployeeProfile")

    profiles = EmployeeProfile.objects.filter(
        manager__isnull=True,
        department__isnull=False,
        department__manager__isnull=False,
    ).select_related("department")

    updated = []
    for profile in profiles:
        # Chỉ gán cho nhân viên. Manager/Admin không có tuyến báo cáo trong
        # mô hình này nên bỏ qua, tránh việc một Manager tự quản lý chính mình.
        if getattr(profile.user.role, "code", None) != "EMPLOYEE":
            continue
        profile.manager_id = profile.department.manager_id
        updated.append(profile)

    if updated:
        EmployeeProfile.objects.bulk_update(updated, ["manager"])


def unset_manager(apps, schema_editor):
    """Chiều ngược lại của backfill, để migration có thể rollback sạch."""
    EmployeeProfile = apps.get_model("accounts", "EmployeeProfile")
    EmployeeProfile.objects.update(manager=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__code': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_manager_from_department, unset_manager),
    ]
