"""
Django settings for worktracker_core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tpqpqakq54&(_ti#z=myx3u$k34l)0!0uk#07x#(=*f^19+)3d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',                 # ASGI server — PHẢI đặt trước staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- CÁC THƯ VIỆN LÕI ĐÃ CÀI QUA PIP ---
    'rest_framework',
    'rest_framework_simplejwt',
    'simple_history',
    'corsheaders',
    "drf_spectacular",
    'django_celery_results',  # Lưu kết quả Celery Task vào DB
    'channels',               # Django Channels — WebSocket layer

    # --- CÁC APP CỦA DỰ ÁN WORK-TRACKER ---
    'accounts',
    'projects',
    'tasks',
    'timesheets',
    'system',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <-- BẮT BUỘC THÊM DÒNG NÀY VÀO ĐÂY
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'worktracker_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'worktracker_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'worktracker_db',
        'USER': 'postgres',          # Tài khoản mặc định của PostgreSQL
        'PASSWORD': '123',  # Thay thế bằng mật khẩu bạn đã đặt khi cài PostgreSQL
        'HOST': '127.0.0.1',
        'PORT': '5432',              # Cổng mặc định của PostgreSQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

# --- CẤU HÌNH LƯU TRỮ FILE (MEDIA) ---
# File upload sẽ lưu vào thư mục media/ trong BASE_DIR
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# CHỈ ĐỊNH SỬ DỤNG BẢNG USER TÙY BIẾN THAY VÌ MẶC ĐỊNH CỦA DJANGO
AUTH_USER_MODEL = 'accounts.CustomUser'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "protocol": 2,
            }
        }
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CachedIsActiveJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "WorkTracker API",
    "DESCRIPTION": "Tài liệu API chính thức cho hệ thống WorkTracker (Manager, Employee, Admin).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# ============================================================
# CELERY — Sử dụng Redis DB=2 (broker) và DB=3 (result)
# Phân tách khỏi Cache (DB=1) để tránh tranh chấp dữ liệu
# ============================================================
CELERY_BROKER_URL = "redis://localhost:6379/2"
CELERY_RESULT_BACKEND = "django-db"   # Lưu vào DB qua django-celery-results
CELERY_CACHE_BACKEND = "django-cache" # Fallback cache backend
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# ============================================================
# DJANGO CHANNELS — Channel Layer dùng Redis DB=4
# Phân tách khỏi Cache (DB=1) và Celery (DB=2, 3)
# ============================================================
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
            "prefix": "worktracker",
            "capacity": 1500,       # Số message tối đa mỗi channel
            "expiry": 60,           # Message hết hạn sau 60 giây nếu không được xử lý
        },
    },
}

# Chỉ định Daphne làm ASGI application (thay Django WSGI mặc định)
ASGI_APPLICATION = "worktracker_core.asgi.application"