[pytest]

# Chỉ định module settings của dự án để pytest biết cách kết nối DB
DJANGO_SETTINGS_MODULE = worktracker_core.settings

# Khai báo các file mà pytest sẽ tự động tìm kiếm để chạy test
python_files = tests.py test_*.py *_tests.py

# Cấu hình bỏ qua các cảnh báo không quan trọng và cấu hình coverage
addopts = -p no:warnings --nomigrations --cov=. --cov-report=html

python_classes = Test*
python_functions = test_*

