# Generated by Django 5.2.15 on 2026-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_client_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
