# Generated by Django 5.2.15 on 2026-08-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_client_id_alter_job_id'),
    ]

    operations = [
    ]
