# Generated by Django 5.2.15 on 2026-09-02 11:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20260810_2128'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('client_name')), name='unique_client_name_case_insensitive'),
        ),
    ]
