# Generated by Django 6.0.6 on 2026-06-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_auditlog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SYSTEM_ONLY', 'System Only'), ('EMAIL_ONLY', 'Email Only'), ('ALL', 'All Channels')], default='SYSTEM_ONLY', max_length=50)),
                ('event_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMMENT', 'Task Comment'), ('TASK_SUBMITTED', 'Task Submitted'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Rejected'), ('TASK_ATTACHMENT', 'Task Attachment'), ('TIMESHEET_LOCK', 'Timesheet Lock'), ('TIMESHEET_UNLOCK', 'Timesheet Unlock'), ('REPORT_EXPORTED', 'Report Exported'), ('ACCOUNT_OR_PERMISSION_CHANGED', 'Account or Permission Changed')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='audit_logs_table_n_c2f649_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
