# Generated by Django 6.0.6 on 2026-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notification_alter_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('NORMAL', 'Normal')], db_index=True, default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
