# Generated by Django 5.2.15 on 2026-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notification_alter_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('NORMAL', 'Normal')], db_index=True, default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
