# Generated by Django 5.2.15 on 2026-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMMENT', 'Task Comment'), ('TASK_SUBMITTED', 'Task Submitted'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Rejected'), ('TASK_ATTACHMENT', 'Task Attachment'), ('LOG_WORK_SUBMITTED', 'Log Work Submitted'), ('LOG_WORK_APPROVED', 'Log Work Approved'), ('LOG_WORK_REJECTED', 'Log Work Rejected'), ('LOG_WORK_VOIDED', 'Log Work Voided'), ('TIMESHEET_LOCK', 'Timesheet Lock'), ('TIMESHEET_UNLOCK', 'Timesheet Unlock'), ('REPORT_EXPORTED', 'Report Exported'), ('ACCOUNT_OR_PERMISSION_CHANGED', 'Account or Permission Changed')], db_index=True, max_length=50),
        ),
    ]
