# Generated by Django 6.0.6 on 2026-06-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWork',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_logs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUserTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'work_date'), name='unique_daily_user_timesheet'), models.CheckConstraint(condition=models.Q(('total_hours__lte', 24)), name='check_total_hours_max_24')],
            },
        ),
        migrations.CreateModel(
            name='TimeLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_month', models.PositiveSmallIntegerField()),
                ('lock_year', models.PositiveSmallIntegerField()),
                ('is_locked', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executed_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lock_month', 'lock_year'), name='unique_lock_month_year')],
            },
        ),
    ]
