# Generated by Django 6.0.6 on 2026-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMMENT', 'Task Comment'), ('TASK_SUBMITTED', 'Task Submitted'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Rejected'), ('TASK_ATTACHMENT', 'Task Attachment'), ('TIMESHEET_LOCK', 'Timesheet Lock'), ('TIMESHEET_UNLOCK', 'Timesheet Unlock'), ('REPORT_EXPORTED', 'Report Exported'), ('ACCOUNT_OR_PERMISSION_CHANGED', 'Account Changed')], db_index=True, default='TASK_ASSIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM_ONLY', 'System Only'), ('EMAIL_ONLY', 'Email Only'), ('ALL', 'All Channels')], default='SYSTEM_ONLY', max_length=50),
        ),
    ]
