# Generated by Django 6.0.6 on 2026-06-29 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_notification_event_type_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelock',
            name='lock_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
