# Generated by Django 6.0.6 on 2026-06-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_client_table_alter_job_table'),
        ('tasks', '0004_alter_taskcomment_comment_type_alter_task_table_and_more'),
        ('timesheets', '0003_alter_timelock_lock_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='timelock',
            name='unique_lock_month_year',
        ),
        migrations.AddField(
            model_name='logwork',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logwork',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_logworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logwork',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logwork',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logwork',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='logwork',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logwork',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelock',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='time_locks', to='projects.job'),
        ),
        migrations.AddField(
            model_name='timelock',
            name='lock_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelock',
            name='lock_scope',
            field=models.CharField(choices=[('JOB', 'Job Scope'), ('GLOBAL', 'Global Scope')], default='JOB', max_length=10),
        ),
        migrations.AddField(
            model_name='timelock',
            name='unlock_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelock',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelock',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyusertimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='logwork',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['PENDING', 'APPROVED', 'REJECTED', 'VOIDED'])), name='check_logwork_review_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='timelock',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', True), ('lock_scope', 'GLOBAL')), fields=('lock_month', 'lock_year'), name='unique_global_lock_per_month'),
        ),
        migrations.AddConstraint(
            model_name='timelock',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False), ('lock_scope', 'JOB')), fields=('lock_month', 'lock_year', 'job'), name='unique_job_lock_per_month_year'),
        ),
        migrations.AddConstraint(
            model_name='timelock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job__isnull', True), ('lock_scope', 'GLOBAL')), models.Q(('job__isnull', False), ('lock_scope', 'JOB')), _connector='OR'), name='check_lock_scope_job_consistency'),
        ),
        migrations.AlterModelTable(
            name='dailyusertimesheet',
            table='daily_user_timesheets',
        ),
        migrations.AlterModelTable(
            name='logwork',
            table='log_works',
        ),
        migrations.AlterModelTable(
            name='timelock',
            table='time_locks',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
    ]
