# Generated by Django 5.2.15 on 2026-07-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_remove_notification_user_remove_taskattachment_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusertimesheet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timelock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
