# Generated by Django 5.2.15 on 2026-08-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_dailyusertimesheet_id_alter_timelock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusertimesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timelock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
