# Generated by Django 6.0.6 on 2026-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_alter_dailyusertimesheet_id_alter_timelock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logwork',
            name='work_date',
            field=models.DateField(db_index=True),
        ),
    ]
