# Generated by Django 6.0.6 on 2026-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='comment_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Discussion'), ('REJECTION_NOTE', 'Rejection Note')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=20),
        ),
    ]
