# Generated by Django 5.2.15 on 2026-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_id_alter_taskattachment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
